<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>cyberpanel-dotnet</AssemblyName>
    <RootNamespace>CyberPanelDotnet</RootNamespace>
    <Version>1.0.9</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
